- name: R
  logo: r
  url: 'https://www.r-project.org/'
  color: '276DC3'
  projects:
    - url: https://github.com/rinterface/shinydashboardplus
    - url: https://github.com/o2r-project/containerit
    - url: https://github.com/tychobra/polished
    - url: https://github.com/jimbrig/rtraining
    - url: https://github.com/jimbrig/jimstaskviews
    - url: https://github.com/jimbrig/github-issue-table
    - url: https://github.com/jimbrig/jimstools
    - url: https://github.com/jimbrig/jimsghstars
    - url: https://github.com/jimbrig/jimstemplates
    - url: https://github.com/jimbrig/Scripts
    - url: https://github.com/jimbrig/lossrx
    - url: https://github.com/jimbrig/lossdevt
    - url: https://github.com/jimbrig/reserver
    - url: https://github.com/jimbrig/actdev
    - url: https://github.com/jimbrig/rsetup
    - url: https://github.com/jimbrig/claimPM
    - url: https://github.com/jimbrig/reserving-insights-app
    - url: https://github.com/jimbrig/eda_app
    - url: https://github.com/jimbrig/loss_development_app
    - url: https://github.com/jimbrig/propallocater
    - url: https://github.com/jimbrig/cookiecutter-r-package
    - url: https://github.com/jimbrig/shiny_react_fliuent_app
    - url: https://github.com/jimbrig/buildtools
    - url: https://github.com/jimbrig/browsr
    - url: https://github.com/jimbrig/profile_app
    - url: https://github.com/jimbrig/EDA
    - url: https://github.com/jimbrig/R_dotfiles_sync
    - url: https://github.com/jimbrig/status
    - url: https://github.com/jimbrig/codemw   
    - url: https://github.com/jimbrig/rpackage-template
    - url: https://github.com/jimbrig/addinslist
    - url: https://github.com/jimbrig/template_shinydashboard
    - url: https://github.com/jimbrig/shinyapp-template
    - url: https://github.com/jimbrig/mustashe
    - url: https://github.com/jimbrig/rsconfig
    - url: https://github.com/jimbrig/phishr
    - url: https://github.com/jimbrig/lossrunAnalyzer
    - url: https://github.com/jimbrig/arsenal
- name: PowerShell
  logo: powershell
  url: https://docs.microsoft.com/en-us/powershell/
  color: '5391FE'
  projects:
    - url: https://github.com/jimbrig/PowerShell
    - url: https://github.com/jimbrig/WindowsPowerShell
    - url: https://github.com/jimbrig/PowerShell-Profiles-Work
    - url: https://github.com/jimbrig/dotfiles
    - url: https://github.com/jimbrig/dotfiles-work
    - url: https://github.com/jimbrig/PSWinSetup
    - url: https://github.com/jimbrig/choco-packages
    - url: https://github.com/jimbrig/winsetup
    - url: https://github.com/jimbrig/Dotfiles-for-Windows-11
    - url: https://github.com/jimbrig/Windows-11-Compatibility-Check
    - url: https://github.com/jimbrig/cloud-adoption-framework
    - url: https://github.com/jimbrig/WindowsSetup
    - url: https://github.com/jimbrig/Scripts-1
    - url: https://github.com/jimbrig/chocolatey-test-environment
    - url: https://github.com/jimbrig/chocolatey-packages
- name: Rust
  logo: rust
  url: 'https://rust.com/'
  color: '643022'
  projects:
    - url: https://github.com/jimbrig/git-cliff
    - url: https://github.com/jimbrig/topgrade
- name: Docker
  logo: docker
  url: 'https://www.docker.com/'
  color: '2496ED'
  projects:
    - url: https://github.com/tychobra/polished
    - url: https://github.com/o2r-project/containerit
    - url: https://github.com/jimbrig/shiny-cloudrun-demo
    - url: https://github.com/jimbrig/shiny-server
    - url: https://github.com/jimbrig/Shiny_app_Azure
    - url: https://github.com/powwater/powpolished
    - url: https://github.com/powwater/vendor_dashboard
- name: PostgreSQL
  logo: postgresql
  url: 'https://postgres.org'
  color: '336791'
  projects:
    - url: https://github.com/powwater/powpolished
    - url: https://github.com/powwater/vendor_dashboard
    - url: https://github.com/jimbrig/postgresql_rest_api
- name: ReactNative
  logo: react
  url: 'https://reactnative.com/'
  color: '61DAFB'
  projects:
    - url: https://github.com/jimbrig/nativeapp
    - url: https://github.com/powwater/flutterwave-react-native
- name: GoogleCloud
  logo: google%20cloud
  url: 'https://cloud.google.com/'
  color: '4285F4'
  projects:
    - url: https://github.com/jimbrig/shiny-cloudrun-demo
    - url: https://github.com/jimbrig/shiny-server
    - url: https://github.com/tychobra/polished
- name: Azure
  logo: microsoft%20azure
  url: 'https://azure.microsoft.com/en-us/'
  color: '0089D6'
  projects:
    - url: https://github.com/jimbrig/Shiny_app_Azure
- name: JavaScript
  logo: javascript
  url: https://javascript.com
  color: 'F7DF1E'
  projects:
    - url: https://github.com/jimbrig/jimsessentials
    - url: https://github.com/powwater/powdocs
- name: HTML
  logo: html5
  url: https://www.w3schools.com/html/
  color: 'E34F26'
  projects:
    - url: https://github.com/powwater/landing_page
- name: Dotfiles
  logo: windows%20terminal
  url: https://docs.microsoft.com/en-us/windows/dev-environment/overview
  color: '4D4D4D'
  projects:
    - url: https://github.com/jimbrig/jimsdots
    - url: https://github.com/jimbrig/rsconfig
    - url: https://github.com/jimbrig/dotfiles-windows
    - url: https://github.com/jimbrig/winsetup
    - url: https://github.com/jimbrig/.github
    - url: https://github.com/jimbrig/r-bucket
    - url: https://github.com/jimbrig/dotfiles-new
- name: Git
  logo: git
  url: https://git-scm.com/
  color: 'F05032'
  projects:
    - url: https://github.com/jimbrig/git-training
- name: MkDocs
  logo: markdown
  url: https://www.mkdocs.org/
  color: '000000'
  projects:
    - url: https://github.com/jimbrig/jimsdocs
    - url: https://github.com/powwater/powdocs
    - url: https://github.com/jimbrig/git-training
- name: GatsbyJS
  logo: gatsby
  url: https://www.gatsbyjs.com/
  color: '663399'
  projects:
    - url: https://github.com/jimbrig/gatsby-cloud-test-site
- name: Excel-VBA
  logo: microsoft%20excel
  url: excel.com
  color: '217346'
  projects:
    - url: https://github.com/jimbrig/xl-macros
