name: Update PSGallery Downloads Badge
on:
  schedule:
  - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      env: 
        GH_USER: 'jimbrig'
        GH_EMAIL: 'jimmy.briggs@jimbrig.com'
    - name: Get PSGallery Downloads
      shell: pwsh
      run: ./.github/scripts/Update-ProfilePSGalleryDownloads.ps1
