name: Todoist Readme

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Update GitHub Profile]
    types:
      - completed

jobs:
  update-readme:
    name: Todoist Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: abhisheknaiidu/todoist-readme@master # jimbrig/todoist-readme@main
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: true
